version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.20.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:7.1.1
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000

  origin:
    build:
      dockerfile: docker/Dockerfile
      context: ./..
    image: ybhutdocker/concurrency-limits-demo
    command: /bin/origin -worker=${ORIGIN_WORKER} -worktime=${ORIGIN_WORKTIME} -queue=${ORIGIN_QUEUE}

  client:
    depends_on:
      - origin
      - proxy
    image: ybhutdocker/concurrency-limits-demo
    command: /bin/client -worker=${CLIENT_WORKER} -rps=${CLIENT_RPS} -origin=${CLIENT_ORIGIN}

  proxy:
    depends_on:
      - origin
    image: ybhutdocker/concurrency-limits-demo
    command: /bin/proxy -quota=${PROXY_QUOTA} -adaptive=${PROXY_ADAPTIVE} -origin=http://origin:8000
    environment:
      - GOMAXPROCS=4
    ports:
      - 7000:7000
